// This file is generated by `_generate.js`. Do not modify by hand.
import { showWhitespaceGlyph, testParser } from '@spyglassmc/core/test-out/utils.js'
import { describe, it } from 'mocha'
import snapshot from 'snap-shot-it'
import { docComments } from '@spyglassmc/mcdoc/lib/parser/index.js'
// @ts-ignore
import { McdocParserTestSuites } from '@spyglassmc/mcdoc/test/parser/_suites.js'

describe('mcdoc docComments', () => {
	for (const content of McdocParserTestSuites['syntax'].docComments.content) {
		it(`Parse "${showWhitespaceGlyph(content)}"`, () => {
			snapshot(testParser(docComments, content))
		})
	}
})
