- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - cron
      - curl

- name: Install acme.sh
  become: true
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      curl https://get.acme.sh | sh -s email={{ acmesh_email }}
    executable: /bin/bash
    creates: /root/.acme.sh/acme.sh

- name: Create certificate directory
  become: true
  ansible.builtin.file:
    path: /etc/nginx/ssl/{{ common_base_domain }}/
    state: directory
    mode: '755'

- name: Add Hurricane Electric dynamic DNS integration
  become: true
  ansible.builtin.copy:
    src: dns_hedyn.sh
    dest: /root/.acme.sh/dnsapi/dns_hedyn.sh
    mode: '755'

- name: Issue certificate
  become: true
  ansible.builtin.shell:
    cmd: |
      set -e
      set -o pipefail
      (umask 066; touch /etc/nginx/ssl/{{ common_base_domain }}/key.pem)
      (umask 022; touch /etc/nginx/ssl/{{ common_base_domain }}/cert.pem)
      export HEdyn_key={{ acmesh_dynamic_dns_key }}
      /root/.acme.sh/acme.sh --issue {% if common_is_prod %}--server letsencrypt{% else %}--staging{% endif %} \
        -d *.{{ common_base_domain }} --dns dns_hedyn
      /root/.acme.sh/acme.sh --install-cert -d *.{{ common_base_domain }} \
        --key-file /etc/nginx/ssl/{{ common_base_domain }}/key.pem \
        --fullchain-file /etc/nginx/ssl/{{ common_base_domain }}/cert.pem \
        --reloadcmd "service nginx reload"
    executable: /bin/bash
    creates: /etc/nginx/ssl/{{ common_base_domain }}/key.pem
