// This file is generated by `_generate.mts`. Do not modify by hand.
import { showWhitespaceGlyph, testParser } from '@spyglassmc/core/test-out/utils.mjs'
import { describe, it } from 'mocha'
import snapshot from 'snap-shot-it'
import { argument } from '@spyglassmc/java-edition/lib/mcfunction/parser/index.mjs'
import type { ArgumentTreeNode } from '@spyglassmc/java-edition/lib/mcfunction/tree/index.mjs'
// @ts-ignore
import { CommandArgumentTestSuites } from '@spyglassmc/java-edition/test/mcfunction/parser/argument/_suites.mjs'
// @ts-ignore
import { meta } from '@spyglassmc/java-edition/test/mcfunction/parser/argument/_meta.mjs'

describe('mcfunction argument minecraft:column_pos', () => {
	for (const { content, properties } of CommandArgumentTestSuites['minecraft:column_pos']!) {
		const treeNode: ArgumentTreeNode = {
			type: 'argument',
			parser: 'minecraft:column_pos',
			properties,
		}
		for (const string of content) {
			it(`Parse "${showWhitespaceGlyph(string)}"${properties ? ` with ${JSON.stringify(properties)}` : ''}`, () => {
				snapshot(testParser(argument(treeNode)!, string, { project: { meta } }))
			})
		}
	}
})
