:page-layout: default
:page-title: Home
:page-has_children: true
:page-nav_order: 1
:page-permalink: /

:link-github-repo: https://github.com/SpyglassMC/Spyglass
:link-l10n: https://l10n.spgoding.com/projects/spyglass/locales/

Welcome to the work-in-progress documentation site for Spyglass, a project that aims at improving your editing experience with Minecraft: Java Edition data packs by providing handy features like auto-completion, real time diagnostics, semantic coloring and such.

The project is under a complete rewrite and is planned to support multiple text editors. For the legacy version of the project commonly known as Data-pack Helper Plus, check out https://marketplace.visualstudio.com/items?itemName=SPGoding.datapack-language-server[the VS Code Marketplace].


== User Testimonials

[quote,slicedlime,'during his https://clips.twitch.tv/TangibleRelentlessGarlicBatChest-wgU7qjHVVmj4Sn5J[Twitch stream]']
____
By far, by a huge margin, the best extension I've found for it.
____

== Getting Started

You can enjoy features provided by Spyglass on various text editors.

=== Sublime Text

Follow the https://github.com/SpyglassMC/LSP-Spyglass#installation[instructions here].

=== VS Code

Install https://marketplace.visualstudio.com/items?itemName=SPGoding.datapack-language-server[from the Marketplace].

=== VSCodium

Install https://open-vsx.org/extension/SPGoding/datapack-language-server[from the Open VSX Registry].

== Customization

Main article: link:./user/config[Config]

== Plugins

The cake is a lie. ALL LIES.

== Mcdoc Specification

Main article: link:./user/mcdoc[Mcdoc]

== Contributing

Ew so many things to write.

* {link-github-repo}/issues/new/choose[Create an issue]
* {link-github-repo}[GitHub Repository]
* {link-l10n}[Localization]
