- name: Install API server
  become: true
  community.general.npm:
    name: '@spyglassmc/web-api-server'
    global: true
    state: latest
  notify: Restart API server service

- name: Create user
  become: true
  block:
    - name: Create group
      ansible.builtin.group:
        name: api-server
        system: true

    - name: Create user
      ansible.builtin.user:
        name: api-server
        group: api-server
        create_home: true
        home: /var/lib/api-server
        system: true

- name: Set up GitHub SSH access
  become: true
  become_user: api-server
  block:
    - name: Create .ssh directory
      ansible.builtin.file:
        path: ~/.ssh
        state: directory
        mode: '700'

    - name: Add GitHub to known_hosts
      ansible.builtin.known_hosts:
        name: github.com
        # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
        key: github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl

    - name: Generate SSH key pair
      community.crypto.openssh_keypair:
        path: ~/.ssh/id_ed25519
        type: ed25519
        comment: 'api-server@{{ ansible_hostname }}'
      notify: Print SSH public key

- name: Create environment files
  become: true
  ansible.builtin.template:
    src: env
    dest: /etc/default/spyglassmc-api-server
    owner: root
    group: root
    mode: '700'
  notify: Restart API server service

- name: Create service
  become: true
  ansible.builtin.copy:
    src: spyglassmc-api-server.service
    dest: /etc/systemd/system/spyglassmc-api-server.service
    mode: '644'
  notify: Reload systemctl daemon

- name: Start service
  become: true
  ansible.builtin.service:
    name: spyglassmc-api-server
    enabled: true
    state: started

- name: Create nginx reverse proxy
  become: true
  ansible.builtin.template:
    src: api-server.conf
    dest: /etc/nginx/conf.d/api-server.conf
    mode: '600'
  notify: Reload nginx
