- name: Add Docker apt repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    architectures: arm64
    uris: https://download.docker.com/linux/debian
    suites: trixie
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
